- hosts: boxfordcnc.lan.london.hackspace.org.uk
  remote_user: root

  tasks:
  - name: "partition the disk"
    script: scripts/01_part

  - name: "set up filesystem"
    script: scripts/02_filesys

  - name: "mount partition"
    script: scripts/03_mount

  - name: "swapon"
    script: scripts/04_swapon

  - name: "debootstrap debian wheezy"
    script: scripts/05_deboo

  - name: "set up fstab"
    script: scripts/06_fstab

  - name: "install grub"
    action: chroot /chroot/cnc/ apt-get install -y grub
  
  - name: "install standard utils"
    action: chroot /chroot/cnc/ apt-get install -y screen rlwrap tcpdump strace git

  - name: "install linux cnc kernel"
    action: "chroot /chroot/cnc/ bash -c \"apt-get update
apt-get dist-upgrade
apt-get install linux-image-rt-686-pae
apt-key adv --keyserver hkp://keys.gnupg.net --recv-key 3cb9fd148f374fef
add-apt-repository 'deb http://linuxcnc.org/ wheezy base 2.7-uspace'
apt-get update
apt-get install linuxcnc-uspace\"
"

  - name: install features
    action: "chroot /chroot/cnc/ bash -c \"apt-get update
apt-get install python-lxml
git clone https://github.com/FernV/NativeCAM.git ~/NativeCAM/
python ~/NativeCAM/setup.py\"
"


  - name: "Reboot"
    action: reboot now "Ansible provision complete"


# Start LinuxCNC with one of these commands (copy/paste) :

# for mill : (axis interface) linuxcnc configs/sim/axis/ncam_demo/mill.ini ; linuxcnc configs/sim/axis/ncam_demo/mill-mm.ini ;

# (gmoccapy interface) linuxcnc configs/sim/gmoccapy/ncam_demo/mill.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/mill-mm.ini ;

# for plasma : (axis interface) linuxcnc configs/sim/axis/ncam_demo/plasma-2d.ini ; linuxcnc configs/sim/axis/ncam_demo/plasma-2d-mm.ini ; linuxcnc configs/sim/axis/ncam_demo/plasma.ini ; linuxcnc configs/sim/axis/ncam_demo/plasma-mm.ini ;

# (gmoccapy interface) linuxcnc configs/sim/gmoccapy/ncam_demo/plasma-2d.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/plasma-2d-mm.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/plasma.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/plasma-mm.ini ;

# for lathe : (not supported yet) linuxcnc configs/sim/axis/ncam_demo/lathe.ini ;

