- hosts: boxfordcnc.lan.london.hackspace.org.uk
  remote_user: root

  tasks:

# dependency checking:

  - script: scripts/t03_done
    register: t03_done
    ignore_errors: True

  - script: scripts/t04_done
    register: t04_done
    ignore_errors: True

  - script: scripts/t05_done
    register: t05_done
    ignore_errors: True

# actual scripts:

  - name: "partition the disk"
    script: scripts/01_part
    when: t03_done|failed

  - name: "set up filesystem"
    script: scripts/02_filesys
    when: t03_done|failed

  - name: "mount partition"
    script: scripts/03_mount
    when: t03_done|failed

  - name: "swapon"
    script: scripts/04_swapon
    when: t04_done|failed

  - name: "debootstrap debian wheezy"
    script: scripts/05_deboo
    when: t05_done|failed

  - name: "set up fstab"
    script: scripts/06_fstab
    args: 
      creates: /chroot/cnc/etc/fstab
# NOTE: creates doesn't actually work; not a problem in this case

  - name: "bind-mount /dev/pts"
    shell: |
      mount --bind /dev/pts /chroot/cnc/dev/pts
# will re-run the bind mount, we just don't care.

  - name: "install standard utils and services"
    command: "chroot /chroot/cnc/ apt-get install -y locales screen rlwrap tcpdump strace git openssh-client openssh-server openntpd vim emacs aptitude"

  - name: "install grub"
    shell: |
      mkdir -p /chroot/cnc/boot/grub
      chroot /chroot/cnc/ apt-get install -y grub
  
  - name: "add LinuxCNC package repository, update package lists"
    shell: |
      chroot /chroot/cnc/ bash -c "
      apt-key adv --keyserver hkp://keys.gnupg.net --recv-key 3cb9fd148f374fef
      apt-get install -y python-software-properties
      add-apt-repository 'deb http://linuxcnc.org/ wheezy base 2.7-uspace'
      apt-get update"

  - name: "install Linux CNC kernel and userspace"
    shell: |
      chroot /chroot/cnc/ bash -c "
      apt-get dist-upgrade
      apt-get install -y linux-image-rt-686-pae
      apt-get install -y linuxcnc-uspace"

  - name: install features
    shell: |
      chroot /chroot/cnc/ bash -c "
      apt-get install -y python-lxml
      git clone https://github.com/FernV/NativeCAM.git ~/NativeCAM/
      python ~/NativeCAM/setup.py"

  - name: "install desktop software"
    command: "chroot /chroot/cnc/ apt-get install -y task-desktop task-xfce-desktop lightdm"

  - name: "add marker for stage 2 detection"
    shell: |
      echo "# Generated by stage 1 from https://github.com/londonhackspace/CNC" > /chroot/cnc/etc/is-CNC-computer

  - name: "make directory for authorized_keys"
    shell: |
      mkdir /chroot/cnc/root/.ssh
      chmod go-rwx /chroot/cnc/root/.ssh

  - name: "add authorized keys before rebooting"
    copy: 
      src: authorized_keys
      dest: /chroot/cnc/root/.ssh/

# XX perms?

  - name: "Issue reboot"
    command: "reboot"

  - name: "Wait for the machine to come back"
    local_action: scripts/wait_for root boxfordcnc.lan.london.hackspace.org.uk

