- hosts: boxfordcnc.lan.london.hackspace.org.uk
  remote_user: root

  tasks:

  - name: "run stage1 script"
    script: scripts/stage1

  - name: "add authorized keys before rebooting"
    copy: 
      src: authorized_keys
      dest: /chroot/cnc/root/.ssh/

# XX perms?

  - name: "Issue reboot"
    command: "reboot"

  - name: "Wait for the machine to come back"
    local_action: shell scripts/wait_for root boxfordcnc.lan.london.hackspace.org.uk

