- hosts: boxfordcnc.lan.london.hackspace.org.uk
  remote_user: root

  tasks:

  - name: "run stage1 script"
    script: scripts/stage1

# XXX ^ why does Ansible not stop (or detect) failures of the stage1 script here??

  - name: "add authorized keys before rebooting"
    copy: 
      src: authorized_keys
      dest: /chroot/cnc/root/.ssh/

# XX perms?

  - name: "Issue reboot"
    script: "scripts/reboot"
    ignore_errors: True

  - name: "Wait for the machine to come back"
    local_action: shell scripts/wait_for root boxfordcnc.lan.london.hackspace.org.uk

