- hosts: boxfordcnc.lan.london.hackspace.org.uk
  remote_user: root

  tasks:

  - name: "update authorized_keys for root"
    copy: 
      src: authorized_keys
      dest: /root/.ssh/

  - name: "change login screen"
    tasks:
    - copy:
        src: greeter.ui.diff
        dest: /usr/share/lightdm-gtk-greeter
    - shell: |
        set -eux
        dpkg-divert --local --rename /usr/share/lightdm-gtk-greeter/greeter.ui 
        cd /usr/share/lightdm-gtk-greeter
        cp greeter.ui.distrib greeter.ui
        patch -p0 < greeter.ui.diff 


# Start LinuxCNC with one of these commands (copy/paste) :

# for mill : (axis interface) linuxcnc configs/sim/axis/ncam_demo/mill.ini ; linuxcnc configs/sim/axis/ncam_demo/mill-mm.ini ;

# (gmoccapy interface) linuxcnc configs/sim/gmoccapy/ncam_demo/mill.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/mill-mm.ini ;

# for plasma : (axis interface) linuxcnc configs/sim/axis/ncam_demo/plasma-2d.ini ; linuxcnc configs/sim/axis/ncam_demo/plasma-2d-mm.ini ; linuxcnc configs/sim/axis/ncam_demo/plasma.ini ; linuxcnc configs/sim/axis/ncam_demo/plasma-mm.ini ;

# (gmoccapy interface) linuxcnc configs/sim/gmoccapy/ncam_demo/plasma-2d.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/plasma-2d-mm.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/plasma.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/plasma-mm.ini ;

# for lathe : (not supported yet) linuxcnc configs/sim/axis/ncam_demo/lathe.ini ;

