- hosts: boxfordcnc.lan.london.hackspace.org.uk
  remote_user: root

  tasks:

  - name: "run stage1"
    local_action: shell localscripts/stage1 {{ inventory_hostname }}

#XX solve this, including swap of ssh keys, or, .ssh/config magic/switchery
#  - name: "Wait for the machine to come back"
#    local_action: shell scripts/wait_for root boxfordcnc.lan.london.hackspace.org.uk

