- hosts: boxfordcnc.lan.london.hackspace.org.uk
  remote_user: root

  tasks:

  - name: "update authorized_keys for root"
    copy: 
      src: authorized_keys
      dest: /root/.ssh/



# Start LinuxCNC with one of these commands (copy/paste) :

# for mill : (axis interface) linuxcnc configs/sim/axis/ncam_demo/mill.ini ; linuxcnc configs/sim/axis/ncam_demo/mill-mm.ini ;

# (gmoccapy interface) linuxcnc configs/sim/gmoccapy/ncam_demo/mill.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/mill-mm.ini ;

# for plasma : (axis interface) linuxcnc configs/sim/axis/ncam_demo/plasma-2d.ini ; linuxcnc configs/sim/axis/ncam_demo/plasma-2d-mm.ini ; linuxcnc configs/sim/axis/ncam_demo/plasma.ini ; linuxcnc configs/sim/axis/ncam_demo/plasma-mm.ini ;

# (gmoccapy interface) linuxcnc configs/sim/gmoccapy/ncam_demo/plasma-2d.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/plasma-2d-mm.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/plasma.ini ; linuxcnc configs/sim/gmoccapy/ncam_demo/plasma-mm.ini ;

# for lathe : (not supported yet) linuxcnc configs/sim/axis/ncam_demo/lathe.ini ;

