#!/bin/bash

set -eu

# XX copy from `scripts/stage1`
if [ -d /etc/CNC-machine-setup ]; then
    echo "Machine is running in stage 2, aborting $0"
    exit 0
fi

reboot

while true; do
    echo "waiting for machine to shut down..."
    sleep 1
done
