#!/bin/bash

test -e /etc/is-CNC-computer

 # stage1 is already done except for the reboot if
 #   test -o /chroot/cnc/etc/is-CNC-computer
 # but probably really also want to know whether the reboot has been done
